/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

import dao.Statistics;
import dao.UserDao;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ManageUsers extends javax.swing.JFrame {

    /**
     * Creates new form ManageUsers
     */
    UserDao user = new UserDao();
    Color textPrimaryColor = new Color(102, 120, 138);
    Color primaryColor = new Color(42, 58, 73);
    int xx, xy;
    DefaultTableModel model;
    int rowIndex;
    Statistics statistics = new Statistics();

    public ManageUsers() {
        initComponents();
        usersTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        passField = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        passAgainField = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ansField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        questField = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        disablePassAgain = new javax.swing.JLabel();
        disablePass = new javax.swing.JLabel();
        enablePass = new javax.swing.JLabel();
        enablePassAgain = new javax.swing.JLabel();
        countryField1 = new javax.swing.JTextField();
        btnBack1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(25, 118, 221));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 744));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("x");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, -1, 40));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ID");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        idField.setEditable(false);
        idField.setBackground(new java.awt.Color(204, 204, 204));
        idField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 302, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Username");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        usernameField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        usernameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameFieldKeyTyped(evt);
            }
        });
        jPanel1.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 302, 30));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Email");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        emailField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 302, 30));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Password");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        passField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passFieldKeyTyped(evt);
            }
        });
        jPanel1.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 300, 30));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Enter Password Again");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        passAgainField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passAgainFieldKeyTyped(evt);
            }
        });
        jPanel1.add(passAgainField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 300, 30));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Security question");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));

        phoneField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(phoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 302, 30));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Phone");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Answer");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, -1, -1));

        ansField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(ansField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 302, 30));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Country");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, -1));

        questField.setEditable(false);
        questField.setBackground(new java.awt.Color(204, 204, 204));
        questField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(questField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 302, 30));

        btnBack.setBackground(new java.awt.Color(255, 102, 102));
        btnBack.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Clear");
        btnBack.setBorderPainted(false);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 300, 40));

        btnSave.setBackground(new java.awt.Color(0, 153, 255));
        btnSave.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Update");
        btnSave.setBorderPainted(false);
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 140, 40));

        disablePassAgain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hide.png"))); // NOI18N
        disablePassAgain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        disablePassAgain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disablePassAgainMouseClicked(evt);
            }
        });
        jPanel1.add(disablePassAgain, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, 30));

        disablePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hide.png"))); // NOI18N
        disablePass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        disablePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disablePassMouseClicked(evt);
            }
        });
        jPanel1.add(disablePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, 30));

        enablePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/visible.png"))); // NOI18N
        enablePass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enablePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enablePassMouseClicked(evt);
            }
        });
        jPanel1.add(enablePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 30, 30));

        enablePassAgain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/visible.png"))); // NOI18N
        enablePassAgain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enablePassAgain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enablePassAgainMouseClicked(evt);
            }
        });
        jPanel1.add(enablePassAgain, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 30, 30));

        countryField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(countryField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 302, 30));

        btnBack1.setBackground(new java.awt.Color(153, 153, 153));
        btnBack1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnBack1.setForeground(new java.awt.Color(255, 255, 255));
        btnBack1.setText("Delete");
        btnBack1.setBorderPainted(false);
        btnBack1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 140, 40));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("______________________________________________________________________________________________________________________________________________");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 720, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "Username", "Email", "Password", "Phone", "Country", "Security Question", "Answer"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 690, 180));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 310, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 60, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usersTable() {
        user.getUsersValue(jTable1, "");
        model = (DefaultTableModel) jTable1.getModel();
        jTable1.setRowHeight(30);
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.BLACK);
        jTable1.setBackground(Color.WHITE);
        jTable1.setSelectionBackground(Color.LIGHT_GRAY);
    }

    public boolean isEmpty() {
        if (usernameField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a user", "Warning", 2);
            return false;
        }

        if (emailField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email address is required", "Warning", 2);
            return false;
        }

        if (!emailField.getText().matches("^.+@.+\\..+$")) {
            JOptionPane.showMessageDialog(this, "Invalid email address", "Warning", 2);
            return false;
        }

        if (String.valueOf(passField.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(this, "Password is required", "Warning", 2);
            return false;
        }
        if (!String.valueOf(passField.getPassword()).matches(String.valueOf(passAgainField.getPassword()))) {
            JOptionPane.showMessageDialog(this, "Password and password again field must be matched", "Warning", 2);
            return false;
        }

        if (phoneField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Phone number is required", "Warning", 2);
            return false;
        }

        if (phoneField.getText().length() > 11 || phoneField.getText().length() < 9) {
            JOptionPane.showMessageDialog(this, "Phone number must be equal 10 character", "Warning", 2);
            return false;
        }

        if (questField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Country field is required", "Warning", 2);
            return false;
        }

        if (ansField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Security answer is required", "Warning", 2);
            return false;
        }

        return true;
    }

    private void clear() {
        usernameField.setText("");
        phoneField.setText("");
        questField.setText("");
        ansField.setText("");
        passField.setText("");
        passAgainField.setText("");
        emailField.setText("");
        jTable1.clearSelection();
        statistics.admin();
    }

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        setVisible(false);
        AdminDashboard.jPanel18.setBackground(primaryColor);
        AdminDashboard.jPanel19.setBackground(primaryColor);
        AdminDashboard.jLabel27.setForeground(textPrimaryColor);
        AdminDashboard.jLabel28.setVisible(true);
        AdminDashboard.jLabel36.setVisible(false);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        clear();
    }//GEN-LAST:event_btnBackActionPerformed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void disablePassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disablePassMouseClicked
        passField.setEchoChar((char) 0);
        disablePass.setVisible(false);
        enablePass.setVisible(true);
    }//GEN-LAST:event_disablePassMouseClicked

    private void disablePassAgainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disablePassAgainMouseClicked
        passAgainField.setEchoChar((char) 0);
        disablePassAgain.setVisible(false);
        enablePassAgain.setVisible(true);
    }//GEN-LAST:event_disablePassAgainMouseClicked

    private void enablePassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enablePassMouseClicked
        passField.setEchoChar('*');
        enablePass.setVisible(false);
        disablePass.setVisible(true);
    }//GEN-LAST:event_enablePassMouseClicked

    private void enablePassAgainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enablePassAgainMouseClicked
        passAgainField.setEchoChar('*');
        disablePassAgain.setVisible(true);
        enablePassAgain.setVisible(false);
    }//GEN-LAST:event_enablePassAgainMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        model = (DefaultTableModel) jTable1.getModel();
        rowIndex = jTable1.getSelectedRow();
        idField.setText(model.getValueAt(rowIndex, 0).toString());
        usernameField.setText(model.getValueAt(rowIndex, 1).toString());
        emailField.setText(model.getValueAt(rowIndex, 2).toString());
        passField.setText(model.getValueAt(rowIndex, 3).toString());
        passAgainField.setText(model.getValueAt(rowIndex, 3).toString());
        phoneField.setText(model.getValueAt(rowIndex, 4).toString());
        questField.setText(model.getValueAt(rowIndex, 6).toString());
        ansField.setText(model.getValueAt(rowIndex, 7).toString());
        countryField1.setText(model.getValueAt(rowIndex, 5).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void usernameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameFieldKeyTyped
        char input = evt.getKeyChar();
        if (!(input < '0' | input > '9') && input != '\b') {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Username mustn't include any number!", "Warning", 2);
        }
    }//GEN-LAST:event_usernameFieldKeyTyped

    private void passFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passFieldKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_passFieldKeyTyped

    private void passAgainFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passAgainFieldKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_passAgainFieldKeyTyped

    private boolean check() {
        String newPhone = phoneField.getText();
        String newEmail = emailField.getText();
        String oldPhone = model.getValueAt(rowIndex, 4).toString();
        String oldEmail = model.getValueAt(rowIndex, 2).toString();
        if (newPhone.equals(oldPhone) && newEmail.equals(oldEmail)) {
            return false;
        } else {
            if (!newEmail.equals(oldEmail)) {
                boolean x = user.isEmailExist(newEmail);
                if (x) {
                    JOptionPane.showMessageDialog(null, "This email is already used", "Warning", 2);
                }
                return x;
            }
            if (!newPhone.equals(oldPhone)) {
                boolean x = user.isPhoneExist(newPhone);
                if (x) {
                    JOptionPane.showMessageDialog(null, "This phone is already used", "Warning", 2);
                }
                return x;
            }
            return false;
        }
    }

    private boolean checkPassword() {
        if (String.valueOf(passField.getPassword()).matches(String.valueOf(passAgainField.getPassword()))) {
            return true;
        }
        return false;
    }

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        jTable1.setModel(new DefaultTableModel(null, new Object[]{"User ID", "Username", "Email",
            "Password", "Phone", "Security Question", "Answer", "Country"}));
        user.getUsersValue(jTable1, jTextField1.getText());
    }//GEN-LAST:event_jTextField1KeyReleased

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (isEmpty()) {
            if (!checkPassword()) {
                JOptionPane.showMessageDialog(null, "Password and password again must match", "Warning", 2);
            }

            if (!check() && checkPassword()) {
                int id = Integer.parseInt(idField.getText());
                String username = usernameField.getText();
                String email = emailField.getText();
                String password = String.valueOf(passField.getPassword());
                String phone = phoneField.getText();
                String seq = questField.getText();
                String ans = ansField.getText();
                String country = countryField1.getText();

                user.updateUser(id, username, email, password, phone, seq, ans, country);
                jTable1.setModel(new DefaultTableModel(null, new Object[]{"User ID", "Username", "Email",
                    "Password", "Phone", "Security Question", "Answer", "Country"}));
                user.getUsersValue(jTable1, "");
                clear();
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        if (isEmpty()) {
            int id = Integer.parseInt(idField.getText());
            user.delete(id);
            jTable1.setModel(new DefaultTableModel(null, new Object[]{"User ID", "Username", "Email",
                "Password", "Phone", "Security Question", "Answer", "Country"}));
            user.getUsersValue(jTable1, "");
            clear();
        }
    }//GEN-LAST:event_btnBack1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ansField;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JLabel btnClose;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField countryField1;
    private javax.swing.JLabel disablePass;
    private javax.swing.JLabel disablePassAgain;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel enablePass;
    private javax.swing.JLabel enablePassAgain;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField passAgainField;
    private javax.swing.JPasswordField passField;
    private javax.swing.JTextField phoneField;
    private javax.swing.JTextField questField;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
